AWSTemplateFormatVersion: "2010-09-09"
Description: "Template simples de CloudFormation para criar EC2 (t2.nano), usuário IAM e bucket S3"

Parameters:
  InstanceType:
    Type: String
    Default: t2.nano
    Description: Tipo da instância EC2
  BucketName:
    Type: String
    Default: desafio-andrea-silva-dio
    Description: Nome do bucket S3 (deve ser globalmente único)
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"
    Description: AMI mais recente do Amazon Linux 2023 via SSM Parameter Store

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: DesafioEC2

  IamUserJoaoSilva:
    Type: AWS::IAM::User
    Properties:
      UserName: joao.silva

  S3BucketDesafio:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  EC2InstanceId:
    Description: ID da instância EC2 criada
    Value: !Ref EC2Instance
  IAMUserArn:
    Description: ARN do usuário IAM criado
    Value: !GetAtt IamUserJoaoSilva.Arn
  S3BucketName:
    Description: Nome do bucket S3 criado
    Value: !Ref S3BucketDesafio
